### ISSUE TITLE
Support for decorating methods

### ISSUE THREAD

**Issue by Rydra** [mplanchard/pydecor#19]
Hello,

I just came across this package and contains several facilities that I find very useful to create expressive code, so I wanted to give it a try. However, when trying to use the "intercept" decorator on an instance method, it seems that the 'self' parameter gets swallowed, raising an error:

```
{TypeError}myfunction() missing 1 required positional argument: 'x'
```

Code example:
```
def _handle_exception(exception):
    exception_name = type(exception).__name__
    if exception_name == 'NoSuchKey':
        raise EntityNotFound('The specified key does not exist')
    else:
        raise exception

... skipping class definition and details...

@intercept(handler=_handle_exception)
def get_node_information(self, key):
     return self._key_to_meta(key)
```

Any workarounds for this case? Thanks!

**Comment by mplanchard** [comment]
Interesting! It's the morning for me and I'm just "heading in" to work, but I'll take a look at this later and get back to you. 👍

**Comment by mplanchard** [comment]
Hey sorry I got distracted last night and forgot about this. I've got a reminder set up to get back to it today!

**Comment by mplanchard** [comment]
Was able to reproduce and opened #20 to fix. I'll get that merged today and push a new release tonight. Thanks for reporting!
